// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/answer': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/answer').default>>>>
    }
    '/api/question': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/question').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/index').default>>>>
    }
  }
}
export {}